title: Stellar
description: >-
  Just another free, fully responsive site <br /> template built by <a href="https://twitter.com/ajlkn">@ajlkn</a> for <a href="https://html5up.net">HTML5 UP</a>
logo: images/logo.svg

address: 1234 Somewhere Road &bull; Nashville, TN 00000 &bull; USA
phone: (000) 000-0000 x 0000
email: information@untitled.tld

socials:
  Twitter: "#"
  Facebook: "#"
  Instagram: "#"
  GitHub: "#"
  Dribbble: "#"
